USE customer_behaviour;
SELECT * FROM customer;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount)
FROM customer
GROUP BY gender;

--  Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND 
      purchase_amount >= (SELECT AVG(purchase_amount)
FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2)
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
GROUP BY shipping_type
HAVING shipping_type IN ('Express' , 'Standard');

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT  subscription_status,
        AVG(purchase_amount) AS avg_spend,
        SUM(purchase_amount) AS total_revenue
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       SUM(purchase_amount) AS total_revenue,
       SUM(purchase_amount) * 100 / (SELECT SUM(purchase_amount)
           FROM customer WHERE discount_applied = 'Yes') AS purchase_pct
FROM customer
WHERE
    discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY purchase_pct DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

with customer_type as(
select case when previous_purchases <=5 then "New "
			when previous_purchases <=15 then "Returning "
			when previous_purchases >15 then "Loyal "
		end as customer_segment 
from customer)
select customer_segment, count(*) from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
with item_count as ( select category, item_purchased, count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) Desc) as item_rank 
from customer group by category, item_purchased
) 
select * from item_count where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT COUNT(customer_id) AS total_count, subscription_status
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group,
       SUM(purchase_amount) AS revenue,
       ROUND(SUM(purchase_amount) * 100 / (SELECT SUM(purchase_amount)
	   FROM customer),2) AS pct_revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC